#!/bin/bash
# Activate the stored TWP definition.
set -e
if [ -f /home/cnc5/linuxcnc-dev/scripts/rip-environment ]; then
    . /home/cnc5/linuxcnc-dev/scripts/rip-environment
fi
halcmd setp headheadtwp.cmd_activate 1
sleep 0.3
halcmd setp headheadtwp.cmd_activate 0
exit 0
