#!/bin/bash
# Reset the stored TWP definition.
set -e
if [ -f /home/cnc5/linuxcnc-dev/scripts/rip-environment ]; then
    . /home/cnc5/linuxcnc-dev/scripts/rip-environment
fi
halcmd setp headheadtwp.cmd_reset 1
sleep 0.3
halcmd setp headheadtwp.cmd_reset 0
exit 0
